name: Build and deploy container image

on:
  push:
    branches:
      - main

permissions:
  id-token: write

env:
  TAG_NAME: opa-server:${{ github.sha }}
  GCP_IMAGE_NAME: asia-northeast1-docker.pkg.dev/mztn-opa-service/opa-server:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build . -t ${{ env.TAG_NAME }}
      - name: Rename image
        run: docker tag ${{ env.TAG_NAME }} ${{ env.GCP_IMAGE_NAME }}
      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v0.4.3"
        with:
          create_credentials_file: "true"
          workload_identity_provider: "projects/531926367161/locations/global/workloadIdentityPools/github-oidc-pool/providers/oidc-github-provider"
          service_account: "deployer@mztn-opa-service.iam.gserviceaccount.com"
      - name: "Login gcloud"
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
      - name: Push image
        run: docker push ${{ env.GCP_IMAGE_NAME }}
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Pushed to ${{ env.GITHUB_IMAGE_NAME }}"
