name: Test OPA policy

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://openpolicyagent/opa:0.35.0-rootless
        with:
          args: "test -v ./policy"
